name: "Docker"

on:
  workflow_dispatch:

  push:
    branches: ["master"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    name: "Build"
    uses: dockette/.github/.github/workflows/docker.yml@master
    secrets: inherit
    with:
        image: "dockette/kumatron"
        tag: "${{ matrix.tag }}"
        context: "${{ matrix.context }}"
    strategy:
      matrix:
        include:
          - tag: latest
            context: .
          - tag: 202403
            context: .

      fail-fast: false
